// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.4
// source: auth_v1.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuthServiceV1Client is the client API for AuthServiceV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthServiceV1Client interface {
	CheckV1(ctx context.Context, in *CheckReqV1, opts ...grpc.CallOption) (*TokenClaimsV1, error)
}

type authServiceV1Client struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceV1Client(cc grpc.ClientConnInterface) AuthServiceV1Client {
	return &authServiceV1Client{cc}
}

func (c *authServiceV1Client) CheckV1(ctx context.Context, in *CheckReqV1, opts ...grpc.CallOption) (*TokenClaimsV1, error) {
	out := new(TokenClaimsV1)
	err := c.cc.Invoke(ctx, "/authServiceV1/CheckV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceV1Server is the server API for AuthServiceV1 service.
// All implementations must embed UnimplementedAuthServiceV1Server
// for forward compatibility
type AuthServiceV1Server interface {
	CheckV1(context.Context, *CheckReqV1) (*TokenClaimsV1, error)
	mustEmbedUnimplementedAuthServiceV1Server()
}

// UnimplementedAuthServiceV1Server must be embedded to have forward compatible implementations.
type UnimplementedAuthServiceV1Server struct {
}

func (UnimplementedAuthServiceV1Server) CheckV1(context.Context, *CheckReqV1) (*TokenClaimsV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckV1 not implemented")
}
func (UnimplementedAuthServiceV1Server) mustEmbedUnimplementedAuthServiceV1Server() {}

// UnsafeAuthServiceV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceV1Server will
// result in compilation errors.
type UnsafeAuthServiceV1Server interface {
	mustEmbedUnimplementedAuthServiceV1Server()
}

func RegisterAuthServiceV1Server(s grpc.ServiceRegistrar, srv AuthServiceV1Server) {
	s.RegisterService(&AuthServiceV1_ServiceDesc, srv)
}

func _AuthServiceV1_CheckV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckReqV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceV1Server).CheckV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authServiceV1/CheckV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceV1Server).CheckV1(ctx, req.(*CheckReqV1))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthServiceV1_ServiceDesc is the grpc.ServiceDesc for AuthServiceV1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthServiceV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "authServiceV1",
	HandlerType: (*AuthServiceV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckV1",
			Handler:    _AuthServiceV1_CheckV1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth_v1.proto",
}
