// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.4
// source: auth_v1.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthRequestV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Type  string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *AuthRequestV1) Reset() {
	*x = AuthRequestV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequestV1) ProtoMessage() {}

func (x *AuthRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequestV1.ProtoReflect.Descriptor instead.
func (*AuthRequestV1) Descriptor() ([]byte, []int) {
	return file_auth_v1_proto_rawDescGZIP(), []int{0}
}

func (x *AuthRequestV1) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthRequestV1) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type AuthResponseV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UID uint64  `protobuf:"varint,1,opt,name=UID,proto3" json:"UID,omitempty"`
	Key *string `protobuf:"bytes,2,opt,name=key,proto3,oneof" json:"key,omitempty"`
}

func (x *AuthResponseV1) Reset() {
	*x = AuthResponseV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_v1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponseV1) ProtoMessage() {}

func (x *AuthResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponseV1.ProtoReflect.Descriptor instead.
func (*AuthResponseV1) Descriptor() ([]byte, []int) {
	return file_auth_v1_proto_rawDescGZIP(), []int{1}
}

func (x *AuthResponseV1) GetUID() uint64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *AuthResponseV1) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

var File_auth_v1_proto protoreflect.FileDescriptor

var file_auth_v1_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x39, 0x0a, 0x0d, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56, 0x31,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x41, 0x0a, 0x0e, 0x41, 0x75,
	0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56, 0x31, 0x12, 0x10, 0x0a, 0x03,
	0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x55, 0x49, 0x44, 0x12, 0x15,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x88, 0x01, 0x01, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x6b, 0x65, 0x79, 0x32, 0x3b, 0x0a,
	0x0d, 0x61, 0x75, 0x74, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x56, 0x31, 0x12, 0x2a,
	0x0a, 0x07, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x56, 0x31, 0x12, 0x0e, 0x2e, 0x41, 0x75, 0x74, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56, 0x31, 0x1a, 0x0f, 0x2e, 0x41, 0x75, 0x74, 0x68,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56, 0x31, 0x42, 0x0d, 0x5a, 0x0b, 0x2f, 0x61,
	0x75, 0x74, 0x68, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_auth_v1_proto_rawDescOnce sync.Once
	file_auth_v1_proto_rawDescData = file_auth_v1_proto_rawDesc
)

func file_auth_v1_proto_rawDescGZIP() []byte {
	file_auth_v1_proto_rawDescOnce.Do(func() {
		file_auth_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_auth_v1_proto_rawDescData)
	})
	return file_auth_v1_proto_rawDescData
}

var file_auth_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_auth_v1_proto_goTypes = []interface{}{
	(*AuthRequestV1)(nil),  // 0: AuthRequestV1
	(*AuthResponseV1)(nil), // 1: AuthResponseV1
}
var file_auth_v1_proto_depIdxs = []int32{
	0, // 0: authServiceV1.CheckV1:input_type -> AuthRequestV1
	1, // 1: authServiceV1.CheckV1:output_type -> AuthResponseV1
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_v1_proto_init() }
func file_auth_v1_proto_init() {
	if File_auth_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_auth_v1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthRequestV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auth_v1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthResponseV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_auth_v1_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_auth_v1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_v1_proto_goTypes,
		DependencyIndexes: file_auth_v1_proto_depIdxs,
		MessageInfos:      file_auth_v1_proto_msgTypes,
	}.Build()
	File_auth_v1_proto = out.File
	file_auth_v1_proto_rawDesc = nil
	file_auth_v1_proto_goTypes = nil
	file_auth_v1_proto_depIdxs = nil
}
